### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [waldolina/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by waldolina** [comment]
@BillyMassey Thanks! I added the meta and it looks like it's re-sizing on my phone, but the nav bar gets pushed together. How do I go about fixing this?

**Comment by BillyMassey** [comment]
I wouldn’t worry too much about fixing this for now.  Later down the line, we’ll teach you how to work with advanced CSS (called media queries), which will allow you to custom tailor CSS for different device widths.  We’ll cover this in the third application (the Flixter app).
